version: "2.1"
services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
    ports:
      - "7002:7002"
    volumes:
      -  /usr/src/app/node_modules
      - ./frontend:/usr/src/app

  backend:
    container_name: backend
    build:
      context: ./backend
    ports:
      - "7001:7001"
    volumes:
      -  /usr/src/app/node_modules
      - ./backend:/usr/src/app
